version: "3.8"

services:
  jupyter:
    build: .
    container_name: pyspark_ml_proyecto
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/work/data
      - ./notebooks:/home/jovyan/work/notebooks
      - ./salidas:/home/jovyan/work/salidas
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYSPARK_SUBMIT_ARGS=--master local[*] pyspark-shell
    deploy:
      resources:
        limits:
          memory: 4g
